### ISSUE TITLE
你为什么不直接给个签名档还得让别人去自己生成？

### ISSUE THREAD

**Issue by K-Guan** [qyecst/install-girlfriend-#1]
![滑稽](http://static.tieba.baidu.com/tb/editor/images/client/image_emoticon25.png)

**Comment by qyecst** [comment]
因为个人电脑用户名主机名不一样，输入命令前的xxxxx@xxxx.xxx:~$不一样，还是自己生成的更像一点

**Comment by K-Guan** [comment]
@qyecst 我知道我只是在开玩笑……话说你在无聊么？

**Comment by qyecst** [comment]
在等吃饭。。。肚子饿啊

**Comment by K-Guan** [comment]
@qyecst 好吧，话说我也在等……

**Comment by qyecst** [comment]
你家也这么迟吃饭？![滑稽](http://static.tieba.baidu.com/tb/editor/images/client/image_emoticon25.png)

**Comment by K-Guan** [comment]
看情况啦……我们在将Github当聊天室用么？

**Comment by qyecst** [comment]
这段对话会被别人看见吗![滑稽](http://static.tieba.baidu.com/tb/editor/images/client/image_emoticon25.png)

**Comment by K-Guan** [comment]
不知道![滑稽](http://static.tieba.baidu.com/tb/editor/images/client/image_emoticon25.png)
